sudo: required
services:
  - docker

before_install:
  - docker build -t flavioseixas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true flavioseixas/docker-react npm run test
  - docker run -e CI=true flavioseixas/docker-react npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
